### ISSUE TITLE
[ERROR] An error occurred while running cordova build android --release (exit code 1).

### ISSUE THREAD

**Issue by g6982** [youzengjian/OdooAppBox#7]
如题，打包出现错误

[ERROR] An error occurred while running cordova build android --release (exit code 1).
        
[22:05:38]  tslint: src/providers/common/common.ts, line: 40 
            't_last_err_msg' is declared but its value is never read. 

      L39:  private _timer_force_dismiss_loading = null;
      L40:  private t_last_err_msg = 0;
      L41:  public app_is_active = true;

[22:05:38]  tslint: src/providers/http/http.ts, line: 60 
            '_get_by_angular_http' is declared but its value is never read. 

      L60:    private _get_by_angular_http(url: string, options?: RequestOptionsArgs): Observable<any> {
      L61:      return new Observable((observer) => {

[22:05:38]  tslint: src/providers/http/http.ts, line: 98 
            '_post_by_angular_http' is declared but its value is never read. 

      L98:    private _post_by_angular_http(url: string, body: string, options?: RequestOptionsArgs): Observable<Respons
      L99:      return new Observable((observer) => {

[22:05:38]  tslint: src/providers/http/http.ts, line: 126 
            'get_image_by_angular_http' is declared but its value is never read. 

     L126:    private get_image_by_angular_http(url:string, options?: RequestOptionsArgs): Observable<any>{
     L127:      return new Observable((observer) => {

[22:05:38]  tslint: src/providers/http/http.ts, line: 13 
            All imports on this line are unused. 

      L12:  import { HTTP, HTTPResponse } from '@ionic-native/http';
      L13:  import VConsole from 'vconsole';
      L14:  import { File, FileEntry } from '@ionic-native/file';

[22:05:38]  tslint: src/app/app.component.ts, line: 4 
            'AfterViewInit' is declared but its value is never read. 

       L4:  import { Component, AfterViewInit, ViewChild } from '@angular/core';
       L5:  import { Platform, App, ToastController } from 'ionic-angular';

[22:05:38]  tslint: src/app/app.component.ts, line: 4 
            'ViewChild' is declared but its value is never read. 

       L4:  import { Component, AfterViewInit, ViewChild } from '@angular/core';
       L5:  import { Platform, App, ToastController } from 'ionic-angular';

[22:05:38]  tslint: src/components/field-boolean/field-boolean.ts, line: 4 
            'Input' is declared but its value is never read. 

       L4:  import { Component, forwardRef, Input } from '@angular/core';
       L5:  import { NG_VALUE_ACCESSOR } from '@angular/forms';

[22:05:38]  tslint: src/components/page-button/page-button.ts, line: 4 
            'OnDestroy' is declared but its value is never read. 

       L4:  import { Component, Input, OnInit, OnDestroy } from '@angular/core';
       L5:  import { CommonProvider, ExceptionActionDefinition } from '../../providers/common/common';

[22:05:38]  tslint: src/pages/form/form.ts, line: 4 
            'OnDestroy' is declared but its value is never read. 

       L4:  wChild, ViewContainerRef, NgModule, Compiler, AfterViewInit, ViewChildren, OnDestroy } from '@angular/core';
       L5:  import { IonicPage, NavController, NavParams, ViewController, AlertController, Content } from 'ionic-angular';

[22:05:38]  tslint: src/pages/home/home.ts, line: 4 
            'ViewChild' is declared but its value is never read. 

       L4:  import { Component, ElementRef, AfterViewInit, ViewChild, ChangeDetectorRef } from '@angular/core';
       L5:  import { IonicPage, NavController } from 'ionic-angular';

[22:05:38]  tslint: src/pages/kanban/kanban.ts, line: 4 
            'OnDestroy' is declared but its value is never read. 

       L4:  import { Component, ViewChild, ViewChildren, OnDestroy, Input } from '@angular/core';
       L5:  import { IonicPage, NavController, NavParams, AlertController, ViewController } from 'ionic-angular';

[22:05:38]  tslint: src/pages/kanban/kanban.ts, line: 4 
            'Input' is declared but its value is never read. 

       L4:  import { Component, ViewChild, ViewChildren, OnDestroy, Input } from '@angular/core';
       L5:  import { IonicPage, NavController, NavParams, AlertController, ViewController } from 'ionic-angular';

[22:05:38]  lint finished in 10.23 s

**Comment by youzengjian** [comment]
信息不全，这边贴的信息只是tslint的提示信息，并不是打包出错的原因。

**Comment by g6982** [comment]
补充信息如下：
> cordova build android --release
Android Studio project detected

Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.
Saved:/Users/baoliang/Desktop/OdooAppBox-master/platforms/android/app/src/main/res/values/strings.xml
Saved:/Users/baoliang/Desktop/OdooAppBox-master/platforms/android/app/src/main/res/values-zh-rCN/strings.xml
[ERROR] An error occurred while running cordova build android --release (exit code 1).

**Comment by youzengjian** [comment]
Failed to find 'ANDROID_HOME' environment variable. Try setting it manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to include path to valid SDK directory.

这两句说明了是安卓SDK未安装或者路径未设置正确，请检查后重试。

建议：按ionic官方的例子搭建环境，确认能正常打包，再尝试打包本项目。
