### ISSUE TITLE
打包安装问题

### ISSUE THREAD

**Issue by cxyryan** [youzengjian/OdooAppBox#8]
android 打包安装后启动提示Application Error net::ERR_FILE_NOT_FOUND (file:///android_asset/www/*)

**Comment by cxyryan** [comment]
ionic info
cli packages: (C:\Users\ryan\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)

local packages:

    @ionic/app-scripts : 3.2.4
    Cordova Platforms  : android 7.1.4 browser 5.0.4 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.17.0
    npm               : 6.13.4
    OS                : Windows 10

Environment Variables:

    ANDROID_HOME : C:\Users\ryan\AppData\Local\Android\Sdk

Misc:

    backend : pro

**Comment by youzengjian** [comment]
打包问题，请检查相关环境和操作

**Comment by cxyryan** [comment]
已解决Application Error net::ERR_FILE_NOT_FOUND (file:///android_asset/www/*)问题，要求包括nodejs版本均一致（8.15.0），ionic cordova build android打包成功并安装运行。但用ionic cordova build android --prod --release打包时，出现新的问题：
[22:01:29]  ngc started ...
[22:01:39]  typescript error
            Cannot determine the module for class BaseFieldComponent in
            C:/Users/ryan/Desktop/projects/OdooAppBox/src/components/base-field/base-field.ts! Add BaseFieldComponent to
            the NgModule to fix it. Cannot determine the module for class RelationalFieldComponent in
            C:/Users/ryan/Desktop/projects/OdooAppBox/src/components/relational-field/relational-field.ts! Add
            RelationalFieldComponent to the NgModule to fix it. Cannot determine the module for class
            AppMenuBaseComponent in
            C:/Users/ryan/Desktop/projects/OdooAppBox/src/components/app-menu-base/app-menu-base.ts! Add
            AppMenuBaseComponent to the NgModule to fix it.

Error: The Angular AoT build failed. See the issues above
    at C:\Users\ryan\Desktop\projects\OdooAppBox\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:237:55
    at step (C:\Users\ryan\Desktop\projects\OdooAppBox\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:32:23)
    at Object.next (C:\Users\ryan\Desktop\projects\OdooAppBox\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:13:53)
    at fulfilled (C:\Users\ryan\Desktop\projects\OdooAppBox\node_modules\@ionic\app-scripts\dist\aot\aot-compiler.js:4:58)
    at <anonymous>

**Comment by youzengjian** [comment]
打包要求的命令是ionic cordova build android --release --optimizejs --minifycss --minifyjs
而不是ionic cordova build android --prod --release

因为当前APP无法使用AOT方式编译，所以不能使用--prod参数
但为了尽量优化，保留了--prod参数默认会使用的--optimizejs --minifycss --minifyjs等参数

**Comment by cxyryan** [comment]
OK，谢谢！签名打包安装成功，继续学习！
