### ISSUE TITLE
请求老大编译个ipa没有签名的，我们自己到网上签名

### ISSUE THREAD

**Issue by zlonn** [youzengjian/OdooAppBox#9]
自己编译后，测试运行 一直在启动界面兜圈，不知道是因为什么。能否编译个ipa，我们自己去外面签名。谢谢老大了

**Comment by youzengjian** [comment]
当前版本代码在指定打包环境下已经过验证，完全没有问题。请自行学习ionic和ios打包相关相关知识完成打包。

**Comment by zlonn** [comment]
但是我们用户比如我，确实是很多人完全不懂技术的
